package com.example.cubetime.utils

import android.content.Context
import android.content.Intent
import com.example.cubetime.data.model.Solve

class Sharing() {
    fun shareSolve(solve: Solve, context: Context) {
        val intent = Intent().apply {
            action = Intent.ACTION_SEND
            putExtra(Intent.EXTRA_TEXT, solveToShare(solve))
            type = "text/plain"
        }
        context.startActivity(intent)
    }


    private fun solveToShare(solve: Solve) : String {
        val time = TimeFormat.millisToString(
            millis = solve.result,
            penalty = solve.penalties
        )
        var result = ""
        result += "Generated by CubeRush on "
        result += solve.date + "\n"
        result += "single: "
        result += time
        result += "\n\nTime List:\n"
        result += "1 .   " + solve.scramble
        return result
    }
}