package com.example.cubetime.utils

import com.example.cubetime.data.model.Solve

object ResultFormat {
    fun solveToShare(solve: Solve) {
        val time = TimeFormat.millisToString(
            millis = solve.result,
            penalty = solve.penalties
        )
        var result = ""
        result += "Generated by CubeRush on "
        result += solve.date + "\n"
        result += "single: "
        result += time
        result += "\n\nTimeList:\n"
        result += "1. " + solve.scramble
    }
}

